# Site settings
title: "Resume of Jens K."
description: "Estonian tinkerer with interests in data science, programming and electronics."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jens K."
resume_title:                   "Software Developer, Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jens@animal.ee"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-"
resume_contact_address:         "-"

resume_header_contact_info:     "-"
display_header_contact_info:    "false"

resume_header_intro: "<p>Ever since I was a teen, I've been experimenting with computers and electronics. Recently I got my first 2 years of work experience in data science and front-end development. Currently I'm studying Computer Engineering in the University of Tartu, but I'm also looking for a (part-time) challenge to sharpen my skills and participate in building something great.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/olafium"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jens-kukk-458194274/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
